version: '3.8'

services:
  app:
    build: .
    container_name: khushaalf-po
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - khushaalf-network

networks:
  khushaalf-network:
    driver: bridge